-Update GITHUB_ACTIONS variable to true in the yml-file -Added listing of the folders

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -30,14 +30,17 @@ jobs:
         TEST_ENV: dev
         USERNAME: ${{ secrets.USERNAME }}
         USERPASSWORD: ${{ secrets.USERPASSWORD }}
-        GITHUB_ACTIONS: false
+        GITHUB_ACTIONS: true
       run: |
           dotnet test --no-build \
             --logger "console;verbosity=normal" \
             -- NUnit.Allure.Configuration.ResultsDirectory=allure-results    
 
-    - name: List allure-results files
-      run: ls -la allure-results
+    - name: List current directory contents
+      run: ls -la
+
+    - name: List allure-results folder (if exists)
+      run: ls -la allure-results || echo "allure-results folder not found"
 
     - name: Upload Allure results as artifact
       uses: actions/upload-artifact@v4
